/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.RoleAccess;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AccessType
 */
public class AccessTypeTest {
    private final AccessType model = new AccessType();

    /**
     * Model tests for AccessType
     */
    @Test
    public void testAccessType() {
        // TODO: test AccessType
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'accessTypeName'
     */
    @Test
    public void accessTypeNameTest() {
        // TODO: test accessTypeName
    }

    /**
     * Test the property 'roleAccess'
     */
    @Test
    public void roleAccessTest() {
        // TODO: test roleAccess
    }

}
