/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.CascadeTiming;
import org.openapitools.client.model.DbContext;
import org.openapitools.client.model.DebugView;
import org.openapitools.client.model.QueryTrackingBehavior;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ChangeTracker
 */
public class ChangeTrackerTest {
    private final ChangeTracker model = new ChangeTracker();

    /**
     * Model tests for ChangeTracker
     */
    @Test
    public void testChangeTracker() {
        // TODO: test ChangeTracker
    }

    /**
     * Test the property 'autoDetectChangesEnabled'
     */
    @Test
    public void autoDetectChangesEnabledTest() {
        // TODO: test autoDetectChangesEnabled
    }

    /**
     * Test the property 'lazyLoadingEnabled'
     */
    @Test
    public void lazyLoadingEnabledTest() {
        // TODO: test lazyLoadingEnabled
    }

    /**
     * Test the property 'queryTrackingBehavior'
     */
    @Test
    public void queryTrackingBehaviorTest() {
        // TODO: test queryTrackingBehavior
    }

    /**
     * Test the property 'deleteOrphansTiming'
     */
    @Test
    public void deleteOrphansTimingTest() {
        // TODO: test deleteOrphansTiming
    }

    /**
     * Test the property 'cascadeDeleteTiming'
     */
    @Test
    public void cascadeDeleteTimingTest() {
        // TODO: test cascadeDeleteTiming
    }

    /**
     * Test the property 'context'
     */
    @Test
    public void contextTest() {
        // TODO: test context
    }

    /**
     * Test the property 'debugView'
     */
    @Test
    public void debugViewTest() {
        // TODO: test debugView
    }

}
