/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.IDbContextTransaction;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DatabaseFacade
 */
public class DatabaseFacadeTest {
    private final DatabaseFacade model = new DatabaseFacade();

    /**
     * Model tests for DatabaseFacade
     */
    @Test
    public void testDatabaseFacade() {
        // TODO: test DatabaseFacade
    }

    /**
     * Test the property 'currentTransaction'
     */
    @Test
    public void currentTransactionTest() {
        // TODO: test currentTransaction
    }

    /**
     * Test the property 'autoTransactionsEnabled'
     */
    @Test
    public void autoTransactionsEnabledTest() {
        // TODO: test autoTransactionsEnabled
    }

    /**
     * Test the property 'providerName'
     */
    @Test
    public void providerNameTest() {
        // TODO: test providerName
    }

}
