/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.ChangeTracker;
import org.openapitools.client.model.DatabaseFacade;
import org.openapitools.client.model.DbContextId;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DbContext
 */
public class DbContextTest {
    private final DbContext model = new DbContext();

    /**
     * Model tests for DbContext
     */
    @Test
    public void testDbContext() {
        // TODO: test DbContext
    }

    /**
     * Test the property 'database'
     */
    @Test
    public void databaseTest() {
        // TODO: test database
    }

    /**
     * Test the property 'changeTracker'
     */
    @Test
    public void changeTrackerTest() {
        // TODO: test changeTracker
    }

    /**
     * Test the property 'model'
     */
    @Test
    public void modelTest() {
        // TODO: test model
    }

    /**
     * Test the property 'contextId'
     */
    @Test
    public void contextIdTest() {
        // TODO: test contextId
    }

}
