/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import org.openapitools.client.model.GearBrand;
import org.openapitools.client.model.UserGear;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Gear
 */
public class GearTest {
    private final Gear model = new Gear();

    /**
     * Model tests for Gear
     */
    @Test
    public void testGear() {
        // TODO: test Gear
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'gearName'
     */
    @Test
    public void gearNameTest() {
        // TODO: test gearName
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'gearPhoto'
     */
    @Test
    public void gearPhotoTest() {
        // TODO: test gearPhoto
    }

    /**
     * Test the property 'gearDesc'
     */
    @Test
    public void gearDescTest() {
        // TODO: test gearDesc
    }

    /**
     * Test the property 'gearBrandId'
     */
    @Test
    public void gearBrandIdTest() {
        // TODO: test gearBrandId
    }

    /**
     * Test the property 'gearBrand'
     */
    @Test
    public void gearBrandTest() {
        // TODO: test gearBrand
    }

    /**
     * Test the property 'userGear'
     */
    @Test
    public void userGearTest() {
        // TODO: test userGear
    }

}
