/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import org.openapitools.client.model.AudioFeedback;
import org.openapitools.client.model.GroupAdminUserDetails;
import org.openapitools.client.model.SongsDetails;
import org.openapitools.client.model.User;
import org.openapitools.client.model.UserGear;
import org.openapitools.client.model.VideoDetails;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GroupAdminDetails
 */
public class GroupAdminDetailsTest {
    private final GroupAdminDetails model = new GroupAdminDetails();

    /**
     * Model tests for GroupAdminDetails
     */
    @Test
    public void testGroupAdminDetails() {
        // TODO: test GroupAdminDetails
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'groupEmail'
     */
    @Test
    public void groupEmailTest() {
        // TODO: test groupEmail
    }

    /**
     * Test the property 'groupName'
     */
    @Test
    public void groupNameTest() {
        // TODO: test groupName
    }

    /**
     * Test the property 'coverLogoPhotoPath'
     */
    @Test
    public void coverLogoPhotoPathTest() {
        // TODO: test coverLogoPhotoPath
    }

    /**
     * Test the property 'logoPhotoPath'
     */
    @Test
    public void logoPhotoPathTest() {
        // TODO: test logoPhotoPath
    }

    /**
     * Test the property 'groupSize'
     */
    @Test
    public void groupSizeTest() {
        // TODO: test groupSize
    }

    /**
     * Test the property 'groupSubscriptionStartDate'
     */
    @Test
    public void groupSubscriptionStartDateTest() {
        // TODO: test groupSubscriptionStartDate
    }

    /**
     * Test the property 'groupSubscriptionEndDate'
     */
    @Test
    public void groupSubscriptionEndDateTest() {
        // TODO: test groupSubscriptionEndDate
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

    /**
     * Test the property 'groupAdminUserDetails'
     */
    @Test
    public void groupAdminUserDetailsTest() {
        // TODO: test groupAdminUserDetails
    }

    /**
     * Test the property 'audioFeedback'
     */
    @Test
    public void audioFeedbackTest() {
        // TODO: test audioFeedback
    }

    /**
     * Test the property 'videoDetails'
     */
    @Test
    public void videoDetailsTest() {
        // TODO: test videoDetails
    }

    /**
     * Test the property 'songsDetails'
     */
    @Test
    public void songsDetailsTest() {
        // TODO: test songsDetails
    }

    /**
     * Test the property 'userGear'
     */
    @Test
    public void userGearTest() {
        // TODO: test userGear
    }

}
