/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.UserGear;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MeasureDistance
 */
public class MeasureDistanceTest {
    private final MeasureDistance model = new MeasureDistance();

    /**
     * Model tests for MeasureDistance
     */
    @Test
    public void testMeasureDistance() {
        // TODO: test MeasureDistance
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'distanceMeasurement'
     */
    @Test
    public void distanceMeasurementTest() {
        // TODO: test distanceMeasurement
    }

    /**
     * Test the property 'userGear'
     */
    @Test
    public void userGearTest() {
        // TODO: test userGear
    }

}
