/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Date;
import org.openapitools.client.model.UserQueryDetails;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for QueryComment
 */
public class QueryCommentTest {
    private final QueryComment model = new QueryComment();

    /**
     * Model tests for QueryComment
     */
    @Test
    public void testQueryComment() {
        // TODO: test QueryComment
    }

    /**
     * Test the property 'queryCommentsID'
     */
    @Test
    public void queryCommentsIDTest() {
        // TODO: test queryCommentsID
    }

    /**
     * Test the property 'userQueryDetailsId'
     */
    @Test
    public void userQueryDetailsIdTest() {
        // TODO: test userQueryDetailsId
    }

    /**
     * Test the property 'userQueryDetails'
     */
    @Test
    public void userQueryDetailsTest() {
        // TODO: test userQueryDetails
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'dateTime'
     */
    @Test
    public void dateTimeTest() {
        // TODO: test dateTime
    }

    /**
     * Test the property 'updatedDateTime'
     */
    @Test
    public void updatedDateTimeTest() {
        // TODO: test updatedDateTime
    }

    /**
     * Test the property 'updatedByUserName'
     */
    @Test
    public void updatedByUserNameTest() {
        // TODO: test updatedByUserName
    }

}
