/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.annotations.SerializedName;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for QueryTrackingBehavior
 */
public class QueryTrackingBehaviorTest {
    /**
     * Model tests for QueryTrackingBehavior
     */
    @Test
    public void testQueryTrackingBehavior() {
        // TODO: test QueryTrackingBehavior
    }

}
