/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.AccessType;
import org.openapitools.client.model.AudioFeedback;
import org.openapitools.client.model.ChangeTracker;
import org.openapitools.client.model.City;
import org.openapitools.client.model.Country;
import org.openapitools.client.model.DatabaseFacade;
import org.openapitools.client.model.DbContextId;
import org.openapitools.client.model.Gear;
import org.openapitools.client.model.GearBrand;
import org.openapitools.client.model.GroupAdminDetails;
import org.openapitools.client.model.GroupAdminUserDetails;
import org.openapitools.client.model.Language;
import org.openapitools.client.model.MeasureDistance;
import org.openapitools.client.model.MeasureHeight;
import org.openapitools.client.model.MeasureWeight;
import org.openapitools.client.model.PasswordResetToken;
import org.openapitools.client.model.ProvinceState;
import org.openapitools.client.model.QueryComment;
import org.openapitools.client.model.QueryMaster;
import org.openapitools.client.model.RefreshToken;
import org.openapitools.client.model.Role;
import org.openapitools.client.model.RoleAccess;
import org.openapitools.client.model.SongsDetails;
import org.openapitools.client.model.Themes;
import org.openapitools.client.model.User;
import org.openapitools.client.model.UserGear;
import org.openapitools.client.model.UserQueryDetails;
import org.openapitools.client.model.UserRole;
import org.openapitools.client.model.VideoDetails;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RPMContext
 */
public class RPMContextTest {
    private final RPMContext model = new RPMContext();

    /**
     * Model tests for RPMContext
     */
    @Test
    public void testRPMContext() {
        // TODO: test RPMContext
    }

    /**
     * Test the property 'database'
     */
    @Test
    public void databaseTest() {
        // TODO: test database
    }

    /**
     * Test the property 'changeTracker'
     */
    @Test
    public void changeTrackerTest() {
        // TODO: test changeTracker
    }

    /**
     * Test the property 'model'
     */
    @Test
    public void modelTest() {
        // TODO: test model
    }

    /**
     * Test the property 'contextId'
     */
    @Test
    public void contextIdTest() {
        // TODO: test contextId
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

    /**
     * Test the property 'userRole'
     */
    @Test
    public void userRoleTest() {
        // TODO: test userRole
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'provinceState'
     */
    @Test
    public void provinceStateTest() {
        // TODO: test provinceState
    }

    /**
     * Test the property 'passwordResetToken'
     */
    @Test
    public void passwordResetTokenTest() {
        // TODO: test passwordResetToken
    }

    /**
     * Test the property 'themes'
     */
    @Test
    public void themesTest() {
        // TODO: test themes
    }

    /**
     * Test the property 'refreshToken'
     */
    @Test
    public void refreshTokenTest() {
        // TODO: test refreshToken
    }

    /**
     * Test the property 'gear'
     */
    @Test
    public void gearTest() {
        // TODO: test gear
    }

    /**
     * Test the property 'gearBrand'
     */
    @Test
    public void gearBrandTest() {
        // TODO: test gearBrand
    }

    /**
     * Test the property 'measureDistance'
     */
    @Test
    public void measureDistanceTest() {
        // TODO: test measureDistance
    }

    /**
     * Test the property 'measureWeight'
     */
    @Test
    public void measureWeightTest() {
        // TODO: test measureWeight
    }

    /**
     * Test the property 'userGear'
     */
    @Test
    public void userGearTest() {
        // TODO: test userGear
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'measureHeight'
     */
    @Test
    public void measureHeightTest() {
        // TODO: test measureHeight
    }

    /**
     * Test the property 'groupAdminDetails'
     */
    @Test
    public void groupAdminDetailsTest() {
        // TODO: test groupAdminDetails
    }

    /**
     * Test the property 'audioFeedback'
     */
    @Test
    public void audioFeedbackTest() {
        // TODO: test audioFeedback
    }

    /**
     * Test the property 'songs'
     */
    @Test
    public void songsTest() {
        // TODO: test songs
    }

    /**
     * Test the property 'videoDetails'
     */
    @Test
    public void videoDetailsTest() {
        // TODO: test videoDetails
    }

    /**
     * Test the property 'groupAdminUserDetails'
     */
    @Test
    public void groupAdminUserDetailsTest() {
        // TODO: test groupAdminUserDetails
    }

    /**
     * Test the property 'queryMaster'
     */
    @Test
    public void queryMasterTest() {
        // TODO: test queryMaster
    }

    /**
     * Test the property 'roleAccess'
     */
    @Test
    public void roleAccessTest() {
        // TODO: test roleAccess
    }

    /**
     * Test the property 'accessType'
     */
    @Test
    public void accessTypeTest() {
        // TODO: test accessType
    }

    /**
     * Test the property 'queryComment'
     */
    @Test
    public void queryCommentTest() {
        // TODO: test queryComment
    }

    /**
     * Test the property 'userQueryDetails'
     */
    @Test
    public void userQueryDetailsTest() {
        // TODO: test userQueryDetails
    }

}
