/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import org.openapitools.client.model.AudioFeedback;
import org.openapitools.client.model.City;
import org.openapitools.client.model.Country;
import org.openapitools.client.model.GroupAdminDetails;
import org.openapitools.client.model.GroupAdminUserDetails;
import org.openapitools.client.model.Language;
import org.openapitools.client.model.MeasureHeight;
import org.openapitools.client.model.MeasureWeight;
import org.openapitools.client.model.ProvinceState;
import org.openapitools.client.model.QueryMaster;
import org.openapitools.client.model.RefreshToken;
import org.openapitools.client.model.RoleAccess;
import org.openapitools.client.model.SongsDetails;
import org.openapitools.client.model.UserGear;
import org.openapitools.client.model.UserQueryDetails;
import org.openapitools.client.model.UserRole;
import org.openapitools.client.model.VideoDetails;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for User
 */
public class UserTest {
    private final User model = new User();

    /**
     * Model tests for User
     */
    @Test
    public void testUser() {
        // TODO: test User
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'fullName'
     */
    @Test
    public void fullNameTest() {
        // TODO: test fullName
    }

    /**
     * Test the property 'age'
     */
    @Test
    public void ageTest() {
        // TODO: test age
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'contactNumber'
     */
    @Test
    public void contactNumberTest() {
        // TODO: test contactNumber
    }

    /**
     * Test the property 'gender'
     */
    @Test
    public void genderTest() {
        // TODO: test gender
    }

    /**
     * Test the property 'cityId'
     */
    @Test
    public void cityIdTest() {
        // TODO: test cityId
    }

    /**
     * Test the property 'provinceStateId'
     */
    @Test
    public void provinceStateIdTest() {
        // TODO: test provinceStateId
    }

    /**
     * Test the property 'countryID'
     */
    @Test
    public void countryIDTest() {
        // TODO: test countryID
    }

    /**
     * Test the property 'languageID'
     */
    @Test
    public void languageIDTest() {
        // TODO: test languageID
    }

    /**
     * Test the property 'dateOfBirth'
     */
    @Test
    public void dateOfBirthTest() {
        // TODO: test dateOfBirth
    }

    /**
     * Test the property 'height'
     */
    @Test
    public void heightTest() {
        // TODO: test height
    }

    /**
     * Test the property 'heightMeasurementId'
     */
    @Test
    public void heightMeasurementIdTest() {
        // TODO: test heightMeasurementId
    }

    /**
     * Test the property 'measureHeight'
     */
    @Test
    public void measureHeightTest() {
        // TODO: test measureHeight
    }

    /**
     * Test the property 'weight'
     */
    @Test
    public void weightTest() {
        // TODO: test weight
    }

    /**
     * Test the property 'weightMeasurementId'
     */
    @Test
    public void weightMeasurementIdTest() {
        // TODO: test weightMeasurementId
    }

    /**
     * Test the property 'measureWeight'
     */
    @Test
    public void measureWeightTest() {
        // TODO: test measureWeight
    }

    /**
     * Test the property 'profilePhoto'
     */
    @Test
    public void profilePhotoTest() {
        // TODO: test profilePhoto
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'isActive'
     */
    @Test
    public void isActiveTest() {
        // TODO: test isActive
    }

    /**
     * Test the property 'isGroup'
     */
    @Test
    public void isGroupTest() {
        // TODO: test isGroup
    }

    /**
     * Test the property 'groupId'
     */
    @Test
    public void groupIdTest() {
        // TODO: test groupId
    }

    /**
     * Test the property 'groupAdminDetails'
     */
    @Test
    public void groupAdminDetailsTest() {
        // TODO: test groupAdminDetails
    }

    /**
     * Test the property 'provinceState'
     */
    @Test
    public void provinceStateTest() {
        // TODO: test provinceState
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'userRole'
     */
    @Test
    public void userRoleTest() {
        // TODO: test userRole
    }

    /**
     * Test the property 'refreshToken'
     */
    @Test
    public void refreshTokenTest() {
        // TODO: test refreshToken
    }

    /**
     * Test the property 'userGear'
     */
    @Test
    public void userGearTest() {
        // TODO: test userGear
    }

    /**
     * Test the property 'audioFeedback'
     */
    @Test
    public void audioFeedbackTest() {
        // TODO: test audioFeedback
    }

    /**
     * Test the property 'songs'
     */
    @Test
    public void songsTest() {
        // TODO: test songs
    }

    /**
     * Test the property 'videoDetails'
     */
    @Test
    public void videoDetailsTest() {
        // TODO: test videoDetails
    }

    /**
     * Test the property 'groupAdminUserDetails'
     */
    @Test
    public void groupAdminUserDetailsTest() {
        // TODO: test groupAdminUserDetails
    }

    /**
     * Test the property 'queryMaster'
     */
    @Test
    public void queryMasterTest() {
        // TODO: test queryMaster
    }

    /**
     * Test the property 'roleAccess'
     */
    @Test
    public void roleAccessTest() {
        // TODO: test roleAccess
    }

    /**
     * Test the property 'userQueryDetails'
     */
    @Test
    public void userQueryDetailsTest() {
        // TODO: test userQueryDetails
    }

}
