/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import org.openapitools.client.model.QueryComment;
import org.openapitools.client.model.User;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UserQueryDetails
 */
public class UserQueryDetailsTest {
    private final UserQueryDetails model = new UserQueryDetails();

    /**
     * Model tests for UserQueryDetails
     */
    @Test
    public void testUserQueryDetails() {
        // TODO: test UserQueryDetails
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'queryId'
     */
    @Test
    public void queryIdTest() {
        // TODO: test queryId
    }

    /**
     * Test the property 'queryMessage'
     */
    @Test
    public void queryMessageTest() {
        // TODO: test queryMessage
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

    /**
     * Test the property 'queryStatus'
     */
    @Test
    public void queryStatusTest() {
        // TODO: test queryStatus
    }

    /**
     * Test the property 'queryComment'
     */
    @Test
    public void queryCommentTest() {
        // TODO: test queryComment
    }

}
