/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Date;
import org.openapitools.client.model.Gear;
import org.openapitools.client.model.GearBrand;
import org.openapitools.client.model.GroupAdminDetails;
import org.openapitools.client.model.MeasureDistance;
import org.openapitools.client.model.Themes;
import org.openapitools.client.model.User;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UserGear
 */
public class UserGearTest {
    private final UserGear model = new UserGear();

    /**
     * Model tests for UserGear
     */
    @Test
    public void testUserGear() {
        // TODO: test UserGear
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'nickname'
     */
    @Test
    public void nicknameTest() {
        // TODO: test nickname
    }

    /**
     * Test the property 'colourId'
     */
    @Test
    public void colourIdTest() {
        // TODO: test colourId
    }

    /**
     * Test the property 'themes'
     */
    @Test
    public void themesTest() {
        // TODO: test themes
    }

    /**
     * Test the property 'maxDistance'
     */
    @Test
    public void maxDistanceTest() {
        // TODO: test maxDistance
    }

    /**
     * Test the property 'distanceMeasurementId'
     */
    @Test
    public void distanceMeasurementIdTest() {
        // TODO: test distanceMeasurementId
    }

    /**
     * Test the property 'measureDistance'
     */
    @Test
    public void measureDistanceTest() {
        // TODO: test measureDistance
    }

    /**
     * Test the property 'isWalking'
     */
    @Test
    public void isWalkingTest() {
        // TODO: test isWalking
    }

    /**
     * Test the property 'isRetired'
     */
    @Test
    public void isRetiredTest() {
        // TODO: test isRetired
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'gearId'
     */
    @Test
    public void gearIdTest() {
        // TODO: test gearId
    }

    /**
     * Test the property 'gear'
     */
    @Test
    public void gearTest() {
        // TODO: test gear
    }

    /**
     * Test the property 'gearBrandId'
     */
    @Test
    public void gearBrandIdTest() {
        // TODO: test gearBrandId
    }

    /**
     * Test the property 'gearBrand'
     */
    @Test
    public void gearBrandTest() {
        // TODO: test gearBrand
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

    /**
     * Test the property 'groupId'
     */
    @Test
    public void groupIdTest() {
        // TODO: test groupId
    }

    /**
     * Test the property 'groupAdminDetails'
     */
    @Test
    public void groupAdminDetailsTest() {
        // TODO: test groupAdminDetails
    }

}
