/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.RoleAccess;
import java.io.Serializable;

/**
 * AccessType
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-27T19:18:22.480284200+05:30[Asia/Calcutta]")
public class AccessType implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_ACCESS_TYPE_NAME = "accessTypeName";
  @SerializedName(SERIALIZED_NAME_ACCESS_TYPE_NAME)
  private String accessTypeName;

  public static final String SERIALIZED_NAME_ROLE_ACCESS = "roleAccess";
  @SerializedName(SERIALIZED_NAME_ROLE_ACCESS)
  private List<RoleAccess> roleAccess = null;


  public AccessType id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public AccessType accessTypeName(String accessTypeName) {
    
    this.accessTypeName = accessTypeName;
    return this;
  }

   /**
   * Get accessTypeName
   * @return accessTypeName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAccessTypeName() {
    return accessTypeName;
  }


  public void setAccessTypeName(String accessTypeName) {
    this.accessTypeName = accessTypeName;
  }


  public AccessType roleAccess(List<RoleAccess> roleAccess) {
    
    this.roleAccess = roleAccess;
    return this;
  }

  public AccessType addRoleAccessItem(RoleAccess roleAccessItem) {
    if (this.roleAccess == null) {
      this.roleAccess = new ArrayList<RoleAccess>();
    }
    this.roleAccess.add(roleAccessItem);
    return this;
  }

   /**
   * Get roleAccess
   * @return roleAccess
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<RoleAccess> getRoleAccess() {
    return roleAccess;
  }


  public void setRoleAccess(List<RoleAccess> roleAccess) {
    this.roleAccess = roleAccess;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccessType accessType = (AccessType) o;
    return Objects.equals(this.id, accessType.id) &&
        Objects.equals(this.accessTypeName, accessType.accessTypeName) &&
        Objects.equals(this.roleAccess, accessType.roleAccess);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, accessTypeName, roleAccess);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccessType {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    accessTypeName: ").append(toIndentedString(accessTypeName)).append("\n");
    sb.append("    roleAccess: ").append(toIndentedString(roleAccess)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

