/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * DebugView
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-27T19:18:22.480284200+05:30[Asia/Calcutta]")
public class DebugView implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_LONG_VIEW = "longView";
  @SerializedName(SERIALIZED_NAME_LONG_VIEW)
  private String longView;

  public static final String SERIALIZED_NAME_SHORT_VIEW = "shortView";
  @SerializedName(SERIALIZED_NAME_SHORT_VIEW)
  private String shortView;


   /**
   * Get longView
   * @return longView
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLongView() {
    return longView;
  }




   /**
   * Get shortView
   * @return shortView
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getShortView() {
    return shortView;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DebugView debugView = (DebugView) o;
    return Objects.equals(this.longView, debugView.longView) &&
        Objects.equals(this.shortView, debugView.shortView);
  }

  @Override
  public int hashCode() {
    return Objects.hash(longView, shortView);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DebugView {\n");
    sb.append("    longView: ").append(toIndentedString(longView)).append("\n");
    sb.append("    shortView: ").append(toIndentedString(shortView)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

