/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * ListUserModel
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-16T14:10:43.971101100+05:30[Asia/Calcutta]")
public class ListUserModel implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_INVITE_USER_ID = "inviteUserId";
  @SerializedName(SERIALIZED_NAME_INVITE_USER_ID)
  private Long inviteUserId;

  public static final String SERIALIZED_NAME_INVITE_USER_NAME = "inviteUserName";
  @SerializedName(SERIALIZED_NAME_INVITE_USER_NAME)
  private String inviteUserName;

  public static final String SERIALIZED_NAME_INVITE_USERCONTACT_NUMBER = "inviteUsercontactNumber";
  @SerializedName(SERIALIZED_NAME_INVITE_USERCONTACT_NUMBER)
  private String inviteUsercontactNumber;

  public static final String SERIALIZED_NAME_INVITE_USER_EMAIL_ID = "inviteUserEmailId";
  @SerializedName(SERIALIZED_NAME_INVITE_USER_EMAIL_ID)
  private String inviteUserEmailId;


  public ListUserModel inviteUserId(Long inviteUserId) {
    
    this.inviteUserId = inviteUserId;
    return this;
  }

   /**
   * Get inviteUserId
   * @return inviteUserId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getInviteUserId() {
    return inviteUserId;
  }


  public void setInviteUserId(Long inviteUserId) {
    this.inviteUserId = inviteUserId;
  }


  public ListUserModel inviteUserName(String inviteUserName) {
    
    this.inviteUserName = inviteUserName;
    return this;
  }

   /**
   * Get inviteUserName
   * @return inviteUserName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getInviteUserName() {
    return inviteUserName;
  }


  public void setInviteUserName(String inviteUserName) {
    this.inviteUserName = inviteUserName;
  }


  public ListUserModel inviteUsercontactNumber(String inviteUsercontactNumber) {
    
    this.inviteUsercontactNumber = inviteUsercontactNumber;
    return this;
  }

   /**
   * Get inviteUsercontactNumber
   * @return inviteUsercontactNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getInviteUsercontactNumber() {
    return inviteUsercontactNumber;
  }


  public void setInviteUsercontactNumber(String inviteUsercontactNumber) {
    this.inviteUsercontactNumber = inviteUsercontactNumber;
  }


  public ListUserModel inviteUserEmailId(String inviteUserEmailId) {
    
    this.inviteUserEmailId = inviteUserEmailId;
    return this;
  }

   /**
   * Get inviteUserEmailId
   * @return inviteUserEmailId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getInviteUserEmailId() {
    return inviteUserEmailId;
  }


  public void setInviteUserEmailId(String inviteUserEmailId) {
    this.inviteUserEmailId = inviteUserEmailId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListUserModel listUserModel = (ListUserModel) o;
    return Objects.equals(this.inviteUserId, listUserModel.inviteUserId) &&
        Objects.equals(this.inviteUserName, listUserModel.inviteUserName) &&
        Objects.equals(this.inviteUsercontactNumber, listUserModel.inviteUsercontactNumber) &&
        Objects.equals(this.inviteUserEmailId, listUserModel.inviteUserEmailId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inviteUserId, inviteUserName, inviteUsercontactNumber, inviteUserEmailId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListUserModel {\n");
    sb.append("    inviteUserId: ").append(toIndentedString(inviteUserId)).append("\n");
    sb.append("    inviteUserName: ").append(toIndentedString(inviteUserName)).append("\n");
    sb.append("    inviteUsercontactNumber: ").append(toIndentedString(inviteUsercontactNumber)).append("\n");
    sb.append("    inviteUserEmailId: ").append(toIndentedString(inviteUserEmailId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

