/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.UserGear;
import java.io.Serializable;

/**
 * MeasureDistance
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-27T19:18:22.480284200+05:30[Asia/Calcutta]")
public class MeasureDistance implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_DISTANCE_MEASUREMENT = "distanceMeasurement";
  @SerializedName(SERIALIZED_NAME_DISTANCE_MEASUREMENT)
  private String distanceMeasurement;

  public static final String SERIALIZED_NAME_USER_GEAR = "userGear";
  @SerializedName(SERIALIZED_NAME_USER_GEAR)
  private List<UserGear> userGear = null;


  public MeasureDistance id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public MeasureDistance distanceMeasurement(String distanceMeasurement) {
    
    this.distanceMeasurement = distanceMeasurement;
    return this;
  }

   /**
   * Get distanceMeasurement
   * @return distanceMeasurement
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDistanceMeasurement() {
    return distanceMeasurement;
  }


  public void setDistanceMeasurement(String distanceMeasurement) {
    this.distanceMeasurement = distanceMeasurement;
  }


  public MeasureDistance userGear(List<UserGear> userGear) {
    
    this.userGear = userGear;
    return this;
  }

  public MeasureDistance addUserGearItem(UserGear userGearItem) {
    if (this.userGear == null) {
      this.userGear = new ArrayList<UserGear>();
    }
    this.userGear.add(userGearItem);
    return this;
  }

   /**
   * Get userGear
   * @return userGear
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<UserGear> getUserGear() {
    return userGear;
  }


  public void setUserGear(List<UserGear> userGear) {
    this.userGear = userGear;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MeasureDistance measureDistance = (MeasureDistance) o;
    return Objects.equals(this.id, measureDistance.id) &&
        Objects.equals(this.distanceMeasurement, measureDistance.distanceMeasurement) &&
        Objects.equals(this.userGear, measureDistance.userGear);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, distanceMeasurement, userGear);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MeasureDistance {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    distanceMeasurement: ").append(toIndentedString(distanceMeasurement)).append("\n");
    sb.append("    userGear: ").append(toIndentedString(userGear)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

