/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.User;
import java.io.Serializable;

/**
 * MeasureHeight
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-27T19:18:22.480284200+05:30[Asia/Calcutta]")
public class MeasureHeight implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_HEIGHT_MEASUREMENT = "heightMeasurement";
  @SerializedName(SERIALIZED_NAME_HEIGHT_MEASUREMENT)
  private String heightMeasurement;

  public static final String SERIALIZED_NAME_USER = "user";
  @SerializedName(SERIALIZED_NAME_USER)
  private List<User> user = null;


  public MeasureHeight id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public MeasureHeight heightMeasurement(String heightMeasurement) {
    
    this.heightMeasurement = heightMeasurement;
    return this;
  }

   /**
   * Get heightMeasurement
   * @return heightMeasurement
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHeightMeasurement() {
    return heightMeasurement;
  }


  public void setHeightMeasurement(String heightMeasurement) {
    this.heightMeasurement = heightMeasurement;
  }


  public MeasureHeight user(List<User> user) {
    
    this.user = user;
    return this;
  }

  public MeasureHeight addUserItem(User userItem) {
    if (this.user == null) {
      this.user = new ArrayList<User>();
    }
    this.user.add(userItem);
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<User> getUser() {
    return user;
  }


  public void setUser(List<User> user) {
    this.user = user;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MeasureHeight measureHeight = (MeasureHeight) o;
    return Objects.equals(this.id, measureHeight.id) &&
        Objects.equals(this.heightMeasurement, measureHeight.heightMeasurement) &&
        Objects.equals(this.user, measureHeight.user);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, heightMeasurement, user);
  }

/*  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MeasureHeight {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    heightMeasurement: ").append(toIndentedString(heightMeasurement)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("}");
    return sb.toString();
  }*/
@Override
public String toString() {
  return heightMeasurement;
}
  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

