/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.AccessType;
import org.openapitools.client.model.Role;
import org.openapitools.client.model.User;
import java.io.Serializable;

/**
 * RoleAccess
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-27T19:18:22.480284200+05:30[Asia/Calcutta]")
public class RoleAccess implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private Long userId;

  public static final String SERIALIZED_NAME_USER = "user";
  @SerializedName(SERIALIZED_NAME_USER)
  private User user;

  public static final String SERIALIZED_NAME_ROLE_ID = "roleId";
  @SerializedName(SERIALIZED_NAME_ROLE_ID)
  private Long roleId;

  public static final String SERIALIZED_NAME_ROLE = "role";
  @SerializedName(SERIALIZED_NAME_ROLE)
  private Role role;

  public static final String SERIALIZED_NAME_ROLE_ACCESS_VALUE = "roleAccessValue";
  @SerializedName(SERIALIZED_NAME_ROLE_ACCESS_VALUE)
  private Boolean roleAccessValue;

  public static final String SERIALIZED_NAME_ACCESS_TYPE_ID = "accessTypeId";
  @SerializedName(SERIALIZED_NAME_ACCESS_TYPE_ID)
  private Long accessTypeId;

  public static final String SERIALIZED_NAME_ACCESS_TYPE = "accessType";
  @SerializedName(SERIALIZED_NAME_ACCESS_TYPE)
  private AccessType accessType;


  public RoleAccess id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public RoleAccess userId(Long userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getUserId() {
    return userId;
  }


  public void setUserId(Long userId) {
    this.userId = userId;
  }


  public RoleAccess user(User user) {
    
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public User getUser() {
    return user;
  }


  public void setUser(User user) {
    this.user = user;
  }


  public RoleAccess roleId(Long roleId) {
    
    this.roleId = roleId;
    return this;
  }

   /**
   * Get roleId
   * @return roleId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getRoleId() {
    return roleId;
  }


  public void setRoleId(Long roleId) {
    this.roleId = roleId;
  }


  public RoleAccess role(Role role) {
    
    this.role = role;
    return this;
  }

   /**
   * Get role
   * @return role
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Role getRole() {
    return role;
  }


  public void setRole(Role role) {
    this.role = role;
  }


  public RoleAccess roleAccessValue(Boolean roleAccessValue) {
    
    this.roleAccessValue = roleAccessValue;
    return this;
  }

   /**
   * Get roleAccessValue
   * @return roleAccessValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getRoleAccessValue() {
    return roleAccessValue;
  }


  public void setRoleAccessValue(Boolean roleAccessValue) {
    this.roleAccessValue = roleAccessValue;
  }


  public RoleAccess accessTypeId(Long accessTypeId) {
    
    this.accessTypeId = accessTypeId;
    return this;
  }

   /**
   * Get accessTypeId
   * @return accessTypeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getAccessTypeId() {
    return accessTypeId;
  }


  public void setAccessTypeId(Long accessTypeId) {
    this.accessTypeId = accessTypeId;
  }


  public RoleAccess accessType(AccessType accessType) {
    
    this.accessType = accessType;
    return this;
  }

   /**
   * Get accessType
   * @return accessType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AccessType getAccessType() {
    return accessType;
  }


  public void setAccessType(AccessType accessType) {
    this.accessType = accessType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RoleAccess roleAccess = (RoleAccess) o;
    return Objects.equals(this.id, roleAccess.id) &&
        Objects.equals(this.userId, roleAccess.userId) &&
        Objects.equals(this.user, roleAccess.user) &&
        Objects.equals(this.roleId, roleAccess.roleId) &&
        Objects.equals(this.role, roleAccess.role) &&
        Objects.equals(this.roleAccessValue, roleAccess.roleAccessValue) &&
        Objects.equals(this.accessTypeId, roleAccess.accessTypeId) &&
        Objects.equals(this.accessType, roleAccess.accessType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, userId, user, roleId, role, roleAccessValue, accessTypeId, accessType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RoleAccess {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    roleId: ").append(toIndentedString(roleId)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    roleAccessValue: ").append(toIndentedString(roleAccessValue)).append("\n");
    sb.append("    accessTypeId: ").append(toIndentedString(accessTypeId)).append("\n");
    sb.append("    accessType: ").append(toIndentedString(accessType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

