/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.RoleAccess;
import org.openapitools.client.model.UserRole;
import java.io.Serializable;

/**
 * Role
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-27T19:18:22.480284200+05:30[Asia/Calcutta]")
public class Role implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_ROLE_NAME = "roleName";
  @SerializedName(SERIALIZED_NAME_ROLE_NAME)
  private String roleName;

  public static final String SERIALIZED_NAME_USER_ROLE = "userRole";
  @SerializedName(SERIALIZED_NAME_USER_ROLE)
  private List<UserRole> userRole = null;

  public static final String SERIALIZED_NAME_ROLE_ACCESS = "roleAccess";
  @SerializedName(SERIALIZED_NAME_ROLE_ACCESS)
  private List<RoleAccess> roleAccess = null;


  public Role id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public Role roleName(String roleName) {
    
    this.roleName = roleName;
    return this;
  }

   /**
   * Get roleName
   * @return roleName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRoleName() {
    return roleName;
  }


  public void setRoleName(String roleName) {
    this.roleName = roleName;
  }


  public Role userRole(List<UserRole> userRole) {
    
    this.userRole = userRole;
    return this;
  }

  public Role addUserRoleItem(UserRole userRoleItem) {
    if (this.userRole == null) {
      this.userRole = new ArrayList<UserRole>();
    }
    this.userRole.add(userRoleItem);
    return this;
  }

   /**
   * Get userRole
   * @return userRole
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<UserRole> getUserRole() {
    return userRole;
  }


  public void setUserRole(List<UserRole> userRole) {
    this.userRole = userRole;
  }


  public Role roleAccess(List<RoleAccess> roleAccess) {
    
    this.roleAccess = roleAccess;
    return this;
  }

  public Role addRoleAccessItem(RoleAccess roleAccessItem) {
    if (this.roleAccess == null) {
      this.roleAccess = new ArrayList<RoleAccess>();
    }
    this.roleAccess.add(roleAccessItem);
    return this;
  }

   /**
   * Get roleAccess
   * @return roleAccess
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<RoleAccess> getRoleAccess() {
    return roleAccess;
  }


  public void setRoleAccess(List<RoleAccess> roleAccess) {
    this.roleAccess = roleAccess;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Role role = (Role) o;
    return Objects.equals(this.id, role.id) &&
        Objects.equals(this.roleName, role.roleName) &&
        Objects.equals(this.userRole, role.userRole) &&
        Objects.equals(this.roleAccess, role.roleAccess);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, roleName, userRole, roleAccess);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Role {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    roleName: ").append(toIndentedString(roleName)).append("\n");
    sb.append("    userRole: ").append(toIndentedString(userRole)).append("\n");
    sb.append("    roleAccess: ").append(toIndentedString(roleAccess)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

