/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Date;
import org.openapitools.client.model.Gear;
import org.openapitools.client.model.GearBrand;
import org.openapitools.client.model.GroupAdminDetails;
import org.openapitools.client.model.MeasureDistance;
import org.openapitools.client.model.Themes;
import org.openapitools.client.model.User;
import java.io.Serializable;

/**
 * UserGear
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-27T19:18:22.480284200+05:30[Asia/Calcutta]")
public class UserGear implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_NICKNAME = "nickname";
  @SerializedName(SERIALIZED_NAME_NICKNAME)
  private String nickname;

  public static final String SERIALIZED_NAME_COLOUR_ID = "colourId";
  @SerializedName(SERIALIZED_NAME_COLOUR_ID)
  private Long colourId;

  public static final String SERIALIZED_NAME_THEMES = "themes";
  @SerializedName(SERIALIZED_NAME_THEMES)
  private Themes themes;

  public static final String SERIALIZED_NAME_MAX_DISTANCE = "maxDistance";
  @SerializedName(SERIALIZED_NAME_MAX_DISTANCE)
  private Long maxDistance;

  public static final String SERIALIZED_NAME_DISTANCE_MEASUREMENT_ID = "distanceMeasurementId";
  @SerializedName(SERIALIZED_NAME_DISTANCE_MEASUREMENT_ID)
  private Long distanceMeasurementId;

  public static final String SERIALIZED_NAME_MEASURE_DISTANCE = "measureDistance";
  @SerializedName(SERIALIZED_NAME_MEASURE_DISTANCE)
  private MeasureDistance measureDistance;

  public static final String SERIALIZED_NAME_IS_WALKING = "isWalking";
  @SerializedName(SERIALIZED_NAME_IS_WALKING)
  private Boolean isWalking;

  public static final String SERIALIZED_NAME_IS_RETIRED = "isRetired";
  @SerializedName(SERIALIZED_NAME_IS_RETIRED)
  private Boolean isRetired;

  public static final String SERIALIZED_NAME_DATE = "date";
  @SerializedName(SERIALIZED_NAME_DATE)
  private Date date;

  public static final String SERIALIZED_NAME_CREATED_DATE = "createdDate";
  @SerializedName(SERIALIZED_NAME_CREATED_DATE)
  private Date createdDate;

  public static final String SERIALIZED_NAME_GEAR_ID = "gearId";
  @SerializedName(SERIALIZED_NAME_GEAR_ID)
  private Long gearId;

  public static final String SERIALIZED_NAME_GEAR = "gear";
  @SerializedName(SERIALIZED_NAME_GEAR)
  private Gear gear;

  public static final String SERIALIZED_NAME_GEAR_BRAND_ID = "gearBrandId";
  @SerializedName(SERIALIZED_NAME_GEAR_BRAND_ID)
  private Long gearBrandId;

  public static final String SERIALIZED_NAME_GEAR_BRAND = "gearBrand";
  @SerializedName(SERIALIZED_NAME_GEAR_BRAND)
  private GearBrand gearBrand;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private Long userId;

  public static final String SERIALIZED_NAME_USER = "user";
  @SerializedName(SERIALIZED_NAME_USER)
  private User user;

  public static final String SERIALIZED_NAME_GROUP_ID = "groupId";
  @SerializedName(SERIALIZED_NAME_GROUP_ID)
  private Long groupId;

  public static final String SERIALIZED_NAME_GROUP_ADMIN_DETAILS = "groupAdminDetails";
  @SerializedName(SERIALIZED_NAME_GROUP_ADMIN_DETAILS)
  private GroupAdminDetails groupAdminDetails;


  public UserGear id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public UserGear nickname(String nickname) {
    
    this.nickname = nickname;
    return this;
  }

   /**
   * Get nickname
   * @return nickname
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNickname() {
    return nickname;
  }


  public void setNickname(String nickname) {
    this.nickname = nickname;
  }


  public UserGear colourId(Long colourId) {
    
    this.colourId = colourId;
    return this;
  }

   /**
   * Get colourId
   * @return colourId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getColourId() {
    return colourId;
  }


  public void setColourId(Long colourId) {
    this.colourId = colourId;
  }


  public UserGear themes(Themes themes) {
    
    this.themes = themes;
    return this;
  }

   /**
   * Get themes
   * @return themes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Themes getThemes() {
    return themes;
  }


  public void setThemes(Themes themes) {
    this.themes = themes;
  }


  public UserGear maxDistance(Long maxDistance) {
    
    this.maxDistance = maxDistance;
    return this;
  }

   /**
   * Get maxDistance
   * @return maxDistance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getMaxDistance() {
    return maxDistance;
  }


  public void setMaxDistance(Long maxDistance) {
    this.maxDistance = maxDistance;
  }


  public UserGear distanceMeasurementId(Long distanceMeasurementId) {
    
    this.distanceMeasurementId = distanceMeasurementId;
    return this;
  }

   /**
   * Get distanceMeasurementId
   * @return distanceMeasurementId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getDistanceMeasurementId() {
    return distanceMeasurementId;
  }


  public void setDistanceMeasurementId(Long distanceMeasurementId) {
    this.distanceMeasurementId = distanceMeasurementId;
  }


  public UserGear measureDistance(MeasureDistance measureDistance) {
    
    this.measureDistance = measureDistance;
    return this;
  }

   /**
   * Get measureDistance
   * @return measureDistance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MeasureDistance getMeasureDistance() {
    return measureDistance;
  }


  public void setMeasureDistance(MeasureDistance measureDistance) {
    this.measureDistance = measureDistance;
  }


  public UserGear isWalking(Boolean isWalking) {
    
    this.isWalking = isWalking;
    return this;
  }

   /**
   * Get isWalking
   * @return isWalking
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsWalking() {
    return isWalking;
  }


  public void setIsWalking(Boolean isWalking) {
    this.isWalking = isWalking;
  }


  public UserGear isRetired(Boolean isRetired) {
    
    this.isRetired = isRetired;
    return this;
  }

   /**
   * Get isRetired
   * @return isRetired
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsRetired() {
    return isRetired;
  }


  public void setIsRetired(Boolean isRetired) {
    this.isRetired = isRetired;
  }


  public UserGear date(Date date) {
    
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Date getDate() {
    return date;
  }


  public void setDate(Date date) {
    this.date = date;
  }


  public UserGear createdDate(Date createdDate) {
    
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Get createdDate
   * @return createdDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Date getCreatedDate() {
    return createdDate;
  }


  public void setCreatedDate(Date createdDate) {
    this.createdDate = createdDate;
  }


  public UserGear gearId(Long gearId) {
    
    this.gearId = gearId;
    return this;
  }

   /**
   * Get gearId
   * @return gearId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getGearId() {
    return gearId;
  }


  public void setGearId(Long gearId) {
    this.gearId = gearId;
  }


  public UserGear gear(Gear gear) {
    
    this.gear = gear;
    return this;
  }

   /**
   * Get gear
   * @return gear
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Gear getGear() {
    return gear;
  }


  public void setGear(Gear gear) {
    this.gear = gear;
  }


  public UserGear gearBrandId(Long gearBrandId) {
    
    this.gearBrandId = gearBrandId;
    return this;
  }

   /**
   * Get gearBrandId
   * @return gearBrandId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getGearBrandId() {
    return gearBrandId;
  }


  public void setGearBrandId(Long gearBrandId) {
    this.gearBrandId = gearBrandId;
  }


  public UserGear gearBrand(GearBrand gearBrand) {
    
    this.gearBrand = gearBrand;
    return this;
  }

   /**
   * Get gearBrand
   * @return gearBrand
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GearBrand getGearBrand() {
    return gearBrand;
  }


  public void setGearBrand(GearBrand gearBrand) {
    this.gearBrand = gearBrand;
  }


  public UserGear userId(Long userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getUserId() {
    return userId;
  }


  public void setUserId(Long userId) {
    this.userId = userId;
  }


  public UserGear user(User user) {
    
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public User getUser() {
    return user;
  }


  public void setUser(User user) {
    this.user = user;
  }


  public UserGear groupId(Long groupId) {
    
    this.groupId = groupId;
    return this;
  }

   /**
   * Get groupId
   * @return groupId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getGroupId() {
    return groupId;
  }


  public void setGroupId(Long groupId) {
    this.groupId = groupId;
  }


  public UserGear groupAdminDetails(GroupAdminDetails groupAdminDetails) {
    
    this.groupAdminDetails = groupAdminDetails;
    return this;
  }

   /**
   * Get groupAdminDetails
   * @return groupAdminDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GroupAdminDetails getGroupAdminDetails() {
    return groupAdminDetails;
  }


  public void setGroupAdminDetails(GroupAdminDetails groupAdminDetails) {
    this.groupAdminDetails = groupAdminDetails;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserGear userGear = (UserGear) o;
    return Objects.equals(this.id, userGear.id) &&
        Objects.equals(this.nickname, userGear.nickname) &&
        Objects.equals(this.colourId, userGear.colourId) &&
        Objects.equals(this.themes, userGear.themes) &&
        Objects.equals(this.maxDistance, userGear.maxDistance) &&
        Objects.equals(this.distanceMeasurementId, userGear.distanceMeasurementId) &&
        Objects.equals(this.measureDistance, userGear.measureDistance) &&
        Objects.equals(this.isWalking, userGear.isWalking) &&
        Objects.equals(this.isRetired, userGear.isRetired) &&
        Objects.equals(this.date, userGear.date) &&
        Objects.equals(this.createdDate, userGear.createdDate) &&
        Objects.equals(this.gearId, userGear.gearId) &&
        Objects.equals(this.gear, userGear.gear) &&
        Objects.equals(this.gearBrandId, userGear.gearBrandId) &&
        Objects.equals(this.gearBrand, userGear.gearBrand) &&
        Objects.equals(this.userId, userGear.userId) &&
        Objects.equals(this.user, userGear.user) &&
        Objects.equals(this.groupId, userGear.groupId) &&
        Objects.equals(this.groupAdminDetails, userGear.groupAdminDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, nickname, colourId, themes, maxDistance, distanceMeasurementId, measureDistance, isWalking, isRetired, date, createdDate, gearId, gear, gearBrandId, gearBrand, userId, user, groupId, groupAdminDetails);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserGear {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nickname: ").append(toIndentedString(nickname)).append("\n");
    sb.append("    colourId: ").append(toIndentedString(colourId)).append("\n");
    sb.append("    themes: ").append(toIndentedString(themes)).append("\n");
    sb.append("    maxDistance: ").append(toIndentedString(maxDistance)).append("\n");
    sb.append("    distanceMeasurementId: ").append(toIndentedString(distanceMeasurementId)).append("\n");
    sb.append("    measureDistance: ").append(toIndentedString(measureDistance)).append("\n");
    sb.append("    isWalking: ").append(toIndentedString(isWalking)).append("\n");
    sb.append("    isRetired: ").append(toIndentedString(isRetired)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    gearId: ").append(toIndentedString(gearId)).append("\n");
    sb.append("    gear: ").append(toIndentedString(gear)).append("\n");
    sb.append("    gearBrandId: ").append(toIndentedString(gearBrandId)).append("\n");
    sb.append("    gearBrand: ").append(toIndentedString(gearBrand)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    groupAdminDetails: ").append(toIndentedString(groupAdminDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

