/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import org.openapitools.client.model.QueryComment;
import org.openapitools.client.model.User;
import java.io.Serializable;

/**
 * UserQueryDetails
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-27T19:18:22.480284200+05:30[Asia/Calcutta]")
public class UserQueryDetails implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_QUERY_ID = "queryId";
  @SerializedName(SERIALIZED_NAME_QUERY_ID)
  private Long queryId;

  public static final String SERIALIZED_NAME_QUERY_MESSAGE = "queryMessage";
  @SerializedName(SERIALIZED_NAME_QUERY_MESSAGE)
  private String queryMessage;

  public static final String SERIALIZED_NAME_CREATED_DATE = "createdDate";
  @SerializedName(SERIALIZED_NAME_CREATED_DATE)
  private Date createdDate;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private Long userId;

  public static final String SERIALIZED_NAME_USER = "user";
  @SerializedName(SERIALIZED_NAME_USER)
  private User user;

  public static final String SERIALIZED_NAME_QUERY_STATUS = "queryStatus";
  @SerializedName(SERIALIZED_NAME_QUERY_STATUS)
  private Integer queryStatus;

  public static final String SERIALIZED_NAME_QUERY_COMMENT = "queryComment";
  @SerializedName(SERIALIZED_NAME_QUERY_COMMENT)
  private List<QueryComment> queryComment = null;


  public UserQueryDetails id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public UserQueryDetails queryId(Long queryId) {
    
    this.queryId = queryId;
    return this;
  }

   /**
   * Get queryId
   * @return queryId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getQueryId() {
    return queryId;
  }


  public void setQueryId(Integer queryId) {
    this.queryId = Long.valueOf(queryId);
  }


  public UserQueryDetails queryMessage(String queryMessage) {
    
    this.queryMessage = queryMessage;
    return this;
  }

   /**
   * Get queryMessage
   * @return queryMessage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getQueryMessage() {
    return queryMessage;
  }


  public void setQueryMessage(String queryMessage) {
    this.queryMessage = queryMessage;
  }


  public UserQueryDetails createdDate(Date createdDate) {
    
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Get createdDate
   * @return createdDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Date getCreatedDate() {
    return createdDate;
  }


  public void setCreatedDate(Date createdDate) {
    this.createdDate = createdDate;
  }


  public UserQueryDetails userId(Long userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getUserId() {
    return userId;
  }


  public void setUserId(Long userId) {
    this.userId = userId;
  }


  public UserQueryDetails user(User user) {
    
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public User getUser() {
    return user;
  }


  public void setUser(User user) {
    this.user = user;
  }


  public UserQueryDetails queryStatus(Integer queryStatus) {
    
    this.queryStatus = queryStatus;
    return this;
  }

   /**
   * Get queryStatus
   * @return queryStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getQueryStatus() {
    return queryStatus;
  }


  public void setQueryStatus(Integer queryStatus) {
    this.queryStatus = queryStatus;
  }


  public UserQueryDetails queryComment(List<QueryComment> queryComment) {
    
    this.queryComment = queryComment;
    return this;
  }

  public UserQueryDetails addQueryCommentItem(QueryComment queryCommentItem) {
    if (this.queryComment == null) {
      this.queryComment = new ArrayList<QueryComment>();
    }
    this.queryComment.add(queryCommentItem);
    return this;
  }

   /**
   * Get queryComment
   * @return queryComment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<QueryComment> getQueryComment() {
    return queryComment;
  }


  public void setQueryComment(List<QueryComment> queryComment) {
    this.queryComment = queryComment;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserQueryDetails userQueryDetails = (UserQueryDetails) o;
    return Objects.equals(this.id, userQueryDetails.id) &&
        Objects.equals(this.queryId, userQueryDetails.queryId) &&
        Objects.equals(this.queryMessage, userQueryDetails.queryMessage) &&
        Objects.equals(this.createdDate, userQueryDetails.createdDate) &&
        Objects.equals(this.userId, userQueryDetails.userId) &&
        Objects.equals(this.user, userQueryDetails.user) &&
        Objects.equals(this.queryStatus, userQueryDetails.queryStatus) &&
        Objects.equals(this.queryComment, userQueryDetails.queryComment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, queryId, queryMessage, createdDate, userId, user, queryStatus, queryComment);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserQueryDetails {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    queryId: ").append(toIndentedString(queryId)).append("\n");
    sb.append("    queryMessage: ").append(toIndentedString(queryMessage)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    queryStatus: ").append(toIndentedString(queryStatus)).append("\n");
    sb.append("    queryComment: ").append(toIndentedString(queryComment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

